### PR TITLE
Bumped TypeScript version to 1.5.0-0

### PR DESCRIPTION
**Pull request by dani-h**

### CODE REVIEW

**Comment by svallory** [comment]
Why?

**Comment by dani-h** [comment]
https://github.com/Microsoft/TypeScript/releases/tag/v1.4

**Comment by svallory** [comment]
Oh, I see. I've been trying to match the typescript-compiler version to typescript version. That's what got me confused.

We have a few problems here though...

- The commit the submodule is pointing to doesn't seem to match tag v1.4 commit
- The build is failing
- The version should be bumped to 1.4, not 1.5

Besides, TS 1.4 exposes an api and it would be better to use that, if possible. But I don't know when I'll be able to get to that, so if you can get it working with the current approach I'll accept it.

Thanks for the help!

**Comment by dani-h** [comment]
I'm actually surprised that the TypeScript team isn't maintaining some sort of programmatic API/wrapper of tsc on their own. It's tiring to keep all sorts of plugins updated whenever they change their version and add new versions or improve compilation speeds.

Regarding the commit: I kind of took a chance forking and submitting this patch because I was in a rush and disregarded the tests. I kind of assumed that 1.3 and 1.5 would be compatible. What are you testing for here exactly besides their CLI? The tests seem to be very extensive(?).

It seems weird that tsc version I found was 1.5 and not 1.4, are the compiler and the language not following the same versioning?

**Comment by svallory** [comment]
I don't know where you found the 1.5v, the language and the command line tool are actually published as a single package.

The tests are extensive because there are many ways to compile typescript.

The API, at least for now, doesn't make the plugin redundant. It's goal was always to provide simple methods for compiling typescript. You could, of course, use the current api to do that, but it's a lot of work and usually doesn't add value to your project. But TS may, eventually, render this plugin irrelevant. Actually, I hope they do :)

**Comment by dani-h** [comment]
Here's where I found the version:
https://github.com/Microsoft/TypeScript/blob/master/package.json

I hope this plugin stays updated as other TS plugins seems to be generally unmaintained. Thank you.

**Comment by svallory** [comment]
Ohh I see. That's under development. It's the `package.json` for the next version, not the current one :)

I'll do my best to keep it up to date, but it's hard to do that when every new version breaks things and I'm the sole developer on this. Anyway... we'll have a new version until the end of the week.

**Comment by dani-h** [comment]
Great (y)

**Comment by svallory** [comment]
Version 1.4.1 is up!

**Pull request closed without merging**
